### ISSUE TITLE
Backtrace 3.6.0 crashes on Backtrace startup on Android 7.0

### ISSUE THREAD

**Issue by hbaInfinity** [backtrace-labs/backtrace-unity#123]
When doing some testing on some older devices for our game, we noticed the game was crashing on our test Samsung Galaxy S6 on start up. After tracking down the issue, we noticed that it was crashing in Backtrace during the initialization code.

Device: Samsung Galaxy S6
OS: Android 7.0
RAM: 3GB

This is the logcat response of the crash:
```
    --------- beginning of crash
2021-10-06 09:51:02.752 17113-17152/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: com.game.productId, PID: 17113
    java.lang.Error: FATAL EXCEPTION [UnityMain]
    Unity version     : 2020.3.18f1
    Device model      : samsung SM-G920I
    Device fingerprint: samsung/zerofltedv/zeroflte:7.0/NRD90M/G920IDVU4FRH2:user/release-keys
    Build Type        : Development
    Scripting Backend : IL2CPP
    ABI               : arm64-v8a
    Strip Engine Code : true
    
    Caused by: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2020.3.18f1 (a7d1c678663c)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'samsung/zerofltedv/zeroflte:7.0/NRD90M/G920IDVU4FRH2:user/release-keys'
    Revision: '11'
    ABI: 'arm64'
    Timestamp: 2021-10-06 09:51:02+1100
    pid: 17113, tid: 17152, name: UnityMain  >>> com.game.productId <<<
    uid: 10182
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    Cause: null pointer dereference
        x0  0000000000000000  x1  0000000000000000  x2  0000000000000028  x3  0000000000000020
        x4  0000000000000021  x5  0000000000000000  x6  0000007d2a027000  x7  0000000000000000
        x8  0000000000000020  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
        x12 0000000000000018  x13 0000000000000000  x14 0000000000000000  x15 0017ba09b1b67a31
        x16 0000007cd7ff8ee0  x17 0000007d284d9080  x18 00000000ed689b3a  x19 0000007cd7ffe090
        x20 0000007cd7e52448  x21 0000007cfbba2ba8  x22 000000000000001d  x23 0000000000200015
        x24 0000000000000001  x25 0000000000200011  x26 000000000020000d  x27 0000007cff797000
        x28 0000000000000001  x29 0000007cfbba26b0
        sp  0000007cfbba2650  lr  0000007cd7e75098  pc  0000007d284d90c4
    
    backtrace:
          #00 pc 000000000001b0c4  /system/lib64/libc.so (memset+68) (BuildId: 0823626294ab008e93e3f03fd5facdee)
          #01 pc 00000000000ed094  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (bun_buffer_init+196) (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #02 pc 00000000000cba8c  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #03 pc 00000000000cb250  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #04 pc 00000000000ca6f8  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #05 pc 00000000000ca620  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #06 pc 00000000000ca578  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #07 pc 00000000000ca550  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #08 pc 00000000000ca51c  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #09 pc 00000000000ca464  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #10 pc 00000000001d6194  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (std::__ndk1::__call_once(unsigned long volatile&, void*, void (*)(void*))+156) (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #11 pc 00000000000c42f0  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #12 pc 00000000000c4234  /data/app/com.game.productId-1/lib/arm64/libbacktrace-native.so (Initialize+136) (BuildId: 587f7e047c66c608f11e96190c3081e3907d981d)
          #13 pc 00000000024afd58  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
2021-10-06 09:51:02.752 17113-17152/? E/AndroidRuntime:       #14 pc 00000000024b1098  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
          #15 pc 00000000024b0a48  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
          #16 pc 00000000024b3d38  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
          #17 pc 0000000001d45b5c  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
          #18 pc 00000000010c5f8c  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
          #19 pc 00000000009d1b40  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
          #20 pc 0000000000c0e2b0  /data/app/com.game.productId-1/lib/arm64/libil2cpp.so (BuildId: 758d2e5076d2ba7b8d3c7de2492d87baa3e58b7e)
          #21 pc 0000000000766724  /data/app/com.game.productId-1/lib/arm64/libunity.so (scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)+164) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #22 pc 00000000007775a4  /data/app/com.game.productId-1/lib/arm64/libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)+156) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #23 pc 0000000000779ce4  /data/app/com.game.productId-1/lib/arm64/libunity.so (ScriptingInvocation::InvokeChecked(ScriptingExceptionPtr*)+52) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #24 pc 00000000007b8a3c  /data/app/com.game.productId-1/lib/arm64/libunity.so (SerializableManagedRef::CallMethod(Object&, ScriptingMethodPtr)+84) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #25 pc 0000000000784fac  /data/app/com.game.productId-1/lib/arm64/libunity.so (MonoBehaviour::CallAwake()+124) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #26 pc 00000000007853c8  /data/app/com.game.productId-1/lib/arm64/libunity.so (MonoBehaviour::AddToManager()+216) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #27 pc 0000000000784f14  /data/app/com.game.productId-1/lib/arm64/libunity.so (MonoBehaviour::AwakeFromLoad(AwakeFromLoadMode)+688) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #28 pc 00000000007d26f0  /data/app/com.game.productId-1/lib/arm64/libunity.so (AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode, bool)+184) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #29 pc 00000000007d2598  /data/app/com.game.productId-1/lib/arm64/libunity.so (AwakeFromLoadQueue::PersistentManagerAwakeFromLoad(int, AwakeFromLoadMode, bool)+136) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #30 pc 00000000007d24f4  /data/app/com.game.productId-1/lib/arm64/libunity.so (AwakeFromLoadQueue::PersistentManagerAwakeFromLoad()+32) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #31 pc 000000000054f31c  /data/app/com.game.productId-1/lib/arm64/libunity.so (LoadSceneOperation::CompleteAwakeSequence()+204) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #32 pc 000000000054f5e4  /data/app/com.game.productId-1/lib/arm64/libunity.so (LoadSceneOperation::CompletePreloadManagerLoadScene()+24) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #33 pc 000000000054ef34  /data/app/com.game.productId-1/lib/arm64/libunity.so (LoadSceneOperation::PlayerLoadSceneFromThread()+488) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #34 pc 000000000054ebe4  /data/app/com.game.productId-1/lib/arm64/libunity.so (LoadSceneOperation::IntegrateMainThread()+168) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
2021-10-06 09:51:02.753 17113-17152/? E/AndroidRuntime:       #35 pc 000000000054feec  /data/app/com.game.productId-1/lib/arm64/libunity.so (PreloadManager::UpdatePreloadingSingleStep(PreloadManager::UpdatePreloadingFlags, int)+276) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #36 pc 00000000005505c4  /data/app/com.game.productId-1/lib/arm64/libunity.so (PreloadManager::WaitForAllAsyncOperationsToComplete()+144) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #37 pc 00000000005508f0  /data/app/com.game.productId-1/lib/arm64/libunity.so (PreloadManager::UpdatePreloading()+184) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #38 pc 0000000000541eb8  /data/app/com.game.productId-1/lib/arm64/libunity.so (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #39 pc 0000000000538a2c  /data/app/com.game.productId-1/lib/arm64/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*)+80) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #40 pc 0000000000538a84  /data/app/com.game.productId-1/lib/arm64/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*)+168) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #41 pc 0000000000538d08  /data/app/com.game.productId-1/lib/arm64/libunity.so (PlayerLoop()+400) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #42 pc 0000000000800c68  /data/app/com.game.productId-1/lib/arm64/libunity.so (UnityPlayerLoop()+744) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #43 pc 0000000000832e80  /data/app/com.game.productId-1/lib/arm64/libunity.so (nativeRender(_JNIEnv*, _jobject*)+72) (BuildId: 47dca361fc71d7ae30e5bef075149d36074e8a0b)
          #44 pc 00000000009fb8a0  /data/app/com.game.productId-1/oat/arm64/base.odex
    
        at libc.memset(memset:68)
        at libbacktrace-native.bun_buffer_init(bun_buffer_init:196)
        at libbacktrace-native.0xcba8c(Native Method)
        at libbacktrace-native.0xcb250(Native Method)
        at libbacktrace-native.0xca6f8(Native Method)
        at libbacktrace-native.0xca620(Native Method)
        at libbacktrace-native.0xca578(Native Method)
        at libbacktrace-native.0xca550(Native Method)
        at libbacktrace-native.0xca51c(Native Method)
        at libbacktrace-native.0xca464(Native Method)
        at libbacktrace-native.std::__ndk1::__call_once(unsigned long volatile&, void*, void (*)(void*))(__call_once:156)
        at libbacktrace-native.0xc42f0(Native Method)
        at libbacktrace-native.Initialize(Initialize:136)
        at libil2cpp.0x24afd58(Native Method)
        at libil2cpp.0x24b1098(Native Method)
        at libil2cpp.0x24b0a48(Native Method)
        at libil2cpp.0x24b3d38(Native Method)
        at libil2cpp.0x1d45b5c(Native Method)
        at libil2cpp.0x10c5f8c(Native Method)
        at libil2cpp.0x9d1b40(Native Method)
        at libil2cpp.0xc0e2b0(Native Method)
        at libunity.scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)(scripting_method_invoke:164)
        at libunity.ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)(Invoke:156)
        at libunity.ScriptingInvocation::InvokeChecked(ScriptingExceptionPtr*)(InvokeChecked:52)
        at libunity.SerializableManagedRef::CallMethod(Object&, ScriptingMethodPtr)(CallMethod:84)
        at libunity.MonoBehaviour::CallAwake()(CallAwake:124)
        at libunity.MonoBehaviour::AddToManager()(AddToManager:216)
        at libunity.MonoBehaviour::AwakeFromLoad(AwakeFromLoadMode)(AwakeFromLoad:688)
        at libunity.AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode, bool)(InvokePersistentManagerAwake:184)
        at libunity.AwakeFromLoadQueue::PersistentManagerAwakeFromLoad(int, AwakeFromLoadMode, bool)(PersistentManagerAwakeFromLoad:136)
        at libunity.AwakeFromLoadQueue::PersistentManagerAwakeFromLoad()(PersistentManagerAwakeFromLoad:32)
        at libunity.LoadSceneOperation::CompleteAwakeSequence()(CompleteAwakeSequence:204)
```

Full Crash Log:
[S6Crash.txt](https://github.com/backtrace-labs/backtrace-unity/files/7360997/S6Crash.txt)

**Comment by hbaInfinity** [comment]
Hey @vlussenburg , Thanks for that. Next thing I was going to do was update to see if it was an issue like that, although seeing what had changed in 3.6.1 and 3.6.2 didn't seem like anything that would have affected only older devices. Luckily it was fixed when we updated to 3.6.2, so it is back up and running on that device now. Thanks.
